In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\vikas\downloads\working projects\infosys spring board\project\.venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\vikas\downloads\working projects\infosys spring board\project\.venv\lib\site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vikas\downloads\working projects\infosys spring board\project\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vikas\downloads\working projects\infosys spring board\project\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vikas\downloads\working projects\infosys spring board\project\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\vikas\downloads\working projects\infosys spring board\project\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
!pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [4]:
import pandas as pd
df = pd.read_excel('../Data/Goals & Assist.xlsx')
df.head()

,Unnamed: 0,Player,Nation,Position,Age,Matches Played,Starts,Minutes,90s Played,Goals,...,Goals Per 90,Assists Per 90,Goals + Assists Per 90,Non-Penalty Goals Per 90,Non-Penalty Goals + Assists Per 90,xG Per 90,xAG Per 90,xG + xAG Per 90,npxG Per 90,npxG + xAG Per 90
0,0,Mohamed Salah,EGY,AT,32,38,38,3371,37.5,29,...,0.77,0.48,1.25,0.53,1.01,0.67,0.38,1.05,0.49,0.87
1,1,Virgil van Dijk,NED,DF,33,37,37,3330,37.0,3,...,0.08,0.03,0.11,0.08,0.11,0.06,0.02,0.08,0.06,0.08
2,2,Ryan Gravenberch,NED,MT,22,37,37,3160,35.1,0,...,0.00,0.11,0.11,0.00,0.11,0.03,0.09,0.12,0.03,0.12
3,3,Alexis Mac Allister,ARG,MT,25,35,30,2599,28.9,5,...,0.17,0.17,0.35,0.17,0.35,0.10,0.16,0.26,0.10,0.26
4,4,Ibrahima Konaté,FRA,DF,25,31,30,2560,28.4,1,...,0.04,0.07,0.11,0.04,0.11,0.06,0.03,0.10,0.06,0.10

In [5]:
columns_to_drop = ['90s Played', 'Goals + Assists', 'Goals Per 90', 'Assists Per 90', 'Goals + Assists Per 90', 'Non-Penalty Goals Per 90', 'Non-Penalty Goals + Assists Per 90', 'xG Per 90', 'xAG Per 90', 'xG + xAG Per 90', 'npxG Per 90', 'npxG + xAG Per 90', 'Yellow Cards', 'Red Cards', 'npxG + xAG']
df = df.drop(columns=columns_to_drop)
df.head()

,Unnamed: 0,Player,Nation,Position,Age,Matches Played,Starts,Minutes,Goals,Assists,Non-Penalty Goals,Penalty Goals Made,Penalty Attempts,xG,npxG,xAG,Progressive Carries,Progressive Passes,Progressive Receives
0,0,Mohamed Salah,EGY,AT,32,38,38,3371,29,18,20,9,9,25.2,18.2,14.2,154,144,488
1,1,Virgil van Dijk,NED,DF,33,37,37,3330,3,1,3,0,0,2.2,2.2,0.7,22,198,6
2,2,Ryan Gravenberch,NED,MT,22,37,37,3160,0,4,0,0,0,1.1,1.1,3.1,70,181,55
3,3,Alexis Mac Allister,ARG,MT,25,35,30,2599,5,5,5,0,0,2.8,2.8,4.7,36,177,80
4,4,Ibrahima Konaté,FRA,DF,25,31,30,2560,1,2,1,0,0,1.7,1.7,1.0,25,115,3